//// this weather api key is generated by https://home.openweathermap.org/api_keys
//// the name of the apiKey is [Default]

const String weatherApiKey = '8080c426c9d56026bb3cd5fe21cbc4f1';

//// the assets paths
const String morningAsset = 'assets/background_morning.png';
const String cloudSunAsset = 'assets/cloud_sun.png';
const String cloudsAsset = 'assets/clouds.png';
const String moonAsset = 'assets/moon.png';
const String nightAsset = 'assets/background_night.png';
const String loadingAsset = 'assets/loading.gif';
